# Dockerfile.spark
FROM apache/spark:3.5.0

USER root
# pip 설치 및 라이브러리 설치
RUN pip install --upgrade pip && \
    pip install python-dotenv pyspark pandas numpy matplotlib scikit-learn kafka-python
USER 185
